services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-container
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  sql-init:
    image: mcr.microsoft.com/mssql-tools:latest
    depends_on:
      - sqlserver
    entrypoint: >
      /bin/bash -c "
      sleep 20;
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P 'YourStrong!Passw0rd' -Q 'CREATE DATABASE BigFileProcessorDb'
      "

volumes:
  sqlserver_data:
